
```{r fig6-pre}
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)
x$num_languages <- vapply (strsplit (x$languages, ","), length,
                           integer (1))
```

```{r fig6-lang-file}
f <- file.path (here, "data-raw", "languages.Rds")
langs_exists <- file.exists (f)
```

```{r fig6-languages, eval = !langs_exists}
lang_one_year <- function (x, year = 2015) {
    x1 <- x |>
        filter (year <= !!year) |>
        group_by (package) |>
        slice_max (date) |>
        mutate (nlangs = mean (num_languages))

    return (mean (x1$nlangs))
}
years <- sort (unique (x$year))
n <- vapply (years, function (i) lang_one_year (x, i),
             numeric (1))
dat <- data.frame (year = years, n = n)
saveRDS (dat, f)
```
```{r fig6A, eval = FALSE}
# Not used!
readRDS (f) |>
    rename (num_languages = n) |>
    ggplot (aes (x = year, y = num_languages)) +
        geom_line () -> p1
```

```{r fig6-fns-per-year-file}
f <- file.path (v_data_dir, "fig06-fns-per-year.Rds")
fns_per_year_exists <- file.exists (f)
```
```{r fig6-nfns-per-year, eval = !fns_per_year_exists}
fns_per_year <- function (x, year = 2015) {

    x1 <- x |>
        filter (year <= !!year) |>
        group_by (package) |>
        slice_max (date)

    x1$loc_R [which (is.na (x1$loc_R))] <- 0L
    x1$loc_src [which (is.na (x1$loc_src))] <- 0L
    x1$loc_inst [which (is.na (x1$loc_inst))] <- 0L
    loc <- x1$loc_R + x1$loc_src + x1$loc_inst

    c (year = year,
       loc = 10 ^ mean (log10 (loc [loc > 0])),
       loc_R = 10 ^ mean (log10 (x1$loc_R [x1$loc_R > 0]), na.rm = TRUE),
       loc_src = 10 ^ mean (log10 (x1$loc_src [x1$loc_src > 0]), na.rm = TRUE),
       loc_inst = 10 ^ mean (log10 (x1$loc_inst [x1$loc_inst > 0]), na.rm = TRUE),
       loc_vignettes = 10 ^ mean (log10 (x1$loc_vignettes [x1$loc_vignettes > 0]), na.rm = TRUE),
       loc_tests = 10 ^ mean (log10 (x1$loc_tests [x1$loc_tests > 0]), na.rm = TRUE),
       n_fns_r_exported = 10 ^ mean (log10 (x1$n_fns_r_exported [x1$n_fns_r_exported > 0]), na.rm = TRUE),
       n_fns_r_not_exported = 10 ^ mean (log10 (x1$n_fns_r_not_exported [x1$n_fns_r_not_exported > 0]), na.rm = TRUE),
       n_fns_src = 10 ^ mean (log10 (x1$n_fns_src [x1$n_fns_src > 0]), na.rm = TRUE),
       n_fns_per_file_r = 10 ^ mean (log10 (x1$n_fns_per_file_r [x1$n_fns_per_file_r > 0]), na.rm = TRUE),
       n_fns_per_file_src = 10 ^ mean (log10 (x1$n_fns_per_file_src [x1$n_fns_per_file_src > 0]), na.rm = TRUE),
       npars_exported_mn = 10 ^ mean (log10 (x1$npars_exported_mn [x1$npars_exported_mn > 0]), na.rm = TRUE),
       npars_exported_md = 10 ^ mean (log10 (x1$npars_exported_md [x1$npars_exported_md > 0]), na.rm = TRUE),
       loc_per_fn_r_mn = 10 ^ mean (log10 (x1$loc_per_fn_r_mn [x1$loc_per_fn_r_mn > 0]), na.rm = TRUE),
       loc_per_fn_r_md = 10 ^ mean (log10 (x1$loc_per_fn_r_md [x1$loc_per_fn_r_md > 0]), na.rm = TRUE),
       loc_per_fn_r_exp_mn = 10 ^ mean (log10 (x1$loc_per_fn_r_exp_mn [x1$loc_per_fn_r_exp_mn > 0]), na.rm = TRUE),
       loc_per_fn_r_exp_md = 10 ^ mean (log10 (x1$loc_per_fn_r_exp_md [x1$loc_per_fn_r_exp_md > 0]), na.rm = TRUE),
       loc_per_fn_r_not_exp_mn = 10 ^ mean (log10 (x1$loc_per_fn_r_not_exp_mn [x1$loc_per_fn_r_not_exp_mn > 0]), na.rm = TRUE),
       loc_per_fn_r_not_exp_md = 10 ^ mean (log10 (x1$loc_per_fn_r_not_exp_md [x1$loc_per_fn_r_not_exp_md > 0]), na.rm = TRUE),
       loc_per_fn_src_mn = 10 ^ mean (log10 (x1$loc_per_fn_src_mn [x1$loc_per_fn_src_mn > 0]), na.rm = TRUE),
       loc_per_fn_src_md = 10 ^ mean (log10 (x1$loc_per_fn_src_md [x1$loc_per_fn_src_md > 0]), na.rm = TRUE),
       doclines_per_fn_exp_mn = 10 ^ mean (log10 (x1$doclines_per_fn_exp_mn [x1$doclines_per_fn_exp_mn > 0]), na.rm = TRUE),
       doclines_per_fn_exp_md = 10 ^ mean (log10 (x1$doclines_per_fn_exp_md [x1$doclines_per_fn_exp_md > 0]), na.rm = TRUE),
       doclines_per_fn_not_exp_mn = 10 ^ mean (log10 (x1$doclines_per_fn_not_exp_mn [x1$doclines_per_fn_not_exp_mn > 0]), na.rm = TRUE),
       doclines_per_fn_not_exp_md = 10 ^ mean (log10 (x1$doclines_per_fn_not_exp_md [x1$doclines_per_fn_not_exp_md > 0]), na.rm = TRUE),
       docchars_per_par_exp_mn = 10 ^ mean (log10 (x1$docchars_per_par_exp_mn [x1$docchars_per_par_exp_mn > 0]), na.rm = TRUE),
       docchars_per_par_exp_md = 10 ^ mean (log10 (x1$docchars_per_par_exp_md [x1$docchars_per_par_exp_md > 0]), na.rm = TRUE))
}
years <- sort (unique (x$year))
dat <- lapply (years, function (i) fns_per_year (x, i))
dat <- data.frame (do.call (rbind, dat))
dat$what <- "cran_by_year"

dat$loc_inst [which (!is.finite (dat$loc_inst))] <- NA

x$loc_R [which (is.na (x$loc_R))] <- 0L
x$loc_src [which (is.na (x$loc_src))] <- 0L
x$loc_inst [which (is.na (x$loc_inst))] <- 0L
x$loc_total <- x$loc_R + x$loc_src + x$loc_inst

xs <- x |>
    group_by (year) |>
    summarise (
        loc = 10 ^ mean (log10 (loc_total [loc_total > 0])),
        loc_R = 10 ^ mean (log10 (loc_R [loc_R > 0]), na.rm = TRUE),
        loc_src = 10 ^ mean (log10 (loc_src [loc_src > 0]), na.rm = TRUE),
        loc_inst = 10 ^ mean (log10 (loc_inst [loc_inst > 0]), na.rm = TRUE),
        loc_vignettes = 10 ^ mean (log10 (loc_vignettes [loc_vignettes > 0]), na.rm = TRUE),
        loc_tests = 10 ^ mean (log10 (loc_tests [loc_tests > 0]), na.rm = TRUE),
        n_fns_r_exported = 10 ^ mean (log10 (n_fns_r_exported [n_fns_r_exported > 0]), na.rm = TRUE),
        n_fns_r_not_exported = 10 ^ mean (log10 (n_fns_r_not_exported [n_fns_r_not_exported > 0]), na.rm = TRUE),
        n_fns_src = 10 ^ mean (log10 (n_fns_src [n_fns_src > 0]), na.rm = TRUE),
        n_fns_per_file_r = 10 ^ mean (log10 (n_fns_per_file_r [n_fns_per_file_r > 0]), na.rm = TRUE),
        n_fns_per_file_src = 10 ^ mean (log10 (n_fns_per_file_src [n_fns_per_file_src > 0]), na.rm = TRUE),
        npars_exported_mn = 10 ^ mean (log10 (npars_exported_mn [npars_exported_mn > 0]), na.rm = TRUE),
        npars_exported_md = 10 ^ mean (log10 (npars_exported_md [npars_exported_md > 0]), na.rm = TRUE),
        loc_per_fn_r_mn = 10 ^ mean (log10 (loc_per_fn_r_mn [loc_per_fn_r_mn > 0]), na.rm = TRUE),
        loc_per_fn_r_md = 10 ^ mean (log10 (loc_per_fn_r_md [loc_per_fn_r_md > 0]), na.rm = TRUE),
        loc_per_fn_r_exp_mn = 10 ^ mean (log10 (loc_per_fn_r_exp_mn [loc_per_fn_r_exp_mn > 0]), na.rm = TRUE),
        loc_per_fn_r_exp_md = 10 ^ mean (log10 (loc_per_fn_r_exp_md [loc_per_fn_r_exp_md > 0]), na.rm = TRUE),
        loc_per_fn_r_not_exp_mn = 10 ^ mean (log10 (loc_per_fn_r_not_exp_mn [loc_per_fn_r_not_exp_mn > 0]), na.rm = TRUE),
        loc_per_fn_r_not_exp_md = 10 ^ mean (log10 (loc_per_fn_r_not_exp_md [loc_per_fn_r_not_exp_md > 0]), na.rm = TRUE),
        loc_per_fn_src_mn = 10 ^ mean (log10 (loc_per_fn_src_mn [loc_per_fn_src_mn > 0]), na.rm = TRUE),
        loc_per_fn_src_md = 10 ^ mean (log10 (loc_per_fn_src_md [loc_per_fn_src_md > 0]), na.rm = TRUE),
        doclines_per_fn_exp_mn = 10 ^ mean (log10 (doclines_per_fn_exp_mn [doclines_per_fn_exp_mn > 0]), na.rm = TRUE),
        doclines_per_fn_exp_md = 10 ^ mean (log10 (doclines_per_fn_exp_md [doclines_per_fn_exp_md > 0]), na.rm = TRUE),
        doclines_per_fn_not_exp_mn = 10 ^ mean (log10 (doclines_per_fn_not_exp_mn [doclines_per_fn_not_exp_mn > 0]), na.rm = TRUE),
        doclines_per_fn_not_exp_md = 10 ^ mean (log10 (doclines_per_fn_not_exp_md [doclines_per_fn_not_exp_md > 0]), na.rm = TRUE),
        docchars_per_par_exp_mn = 10 ^ mean (log10 (docchars_per_par_exp_mn [docchars_per_par_exp_mn > 0]), na.rm = TRUE),
        docchars_per_par_exp_md = 10 ^ mean (log10 (docchars_per_par_exp_md [docchars_per_par_exp_md > 0]), na.rm = TRUE))
xs$what <- "annual"

saveRDS (rbind (dat, xs), f)
```

```{r fig6A-loc-per-year-plot}
loc <- readRDS (f)
loc_cran <- loc |>
    filter (what == "cran_by_year") |>
    select (c (year, loc, loc_R, loc_src, loc_inst)) |>
    rename (total = loc,
            R = loc_R,
            src = loc_src,
            inst = loc_inst) |>
    pivot_longer (c (total, R, src, inst)) |>
    rename (type = name, number = value)
loc |>
    filter (what == "annual") |>
    select (c (year, loc, loc_R, loc_src, loc_inst)) |>
    rename (total = loc,
            R = loc_R,
            src = loc_src,
            inst = loc_inst) |>
    #mutate (total = total * max (inst, na.rm = TRUE) / max (total, na.rm = TRUE)) |>
    pivot_longer (c (total, R, src, inst)) |>
    rename (type = name, number = value) |>
    ggplot (aes (x = year, y = number, colour = type)) +
        geom_line () +
        #geom_line (data = loc_cran, show.legend = FALSE, lty = 2) +
        theme (legend.title = element_blank(),
               legend.position = c (0.2, 0.85),
               legend.background = element_rect(fill='transparent', colour='transparent')) +
        ylab ("Lines of Code") +
        guides (color = guide_legend (ncol = 2)) +
        ggtitle ("A: Lines of Code") -> p1
```

```{r fig6B-loc-per-fn}
loc_cran <- readRDS (f) |>
    filter (what == "cran_by_year") |>
    select (c (year, loc_per_fn_r_exp_mn, loc_per_fn_r_not_exp_mn,
               loc_per_fn_src_mn)) |>
    rename (R_exp = loc_per_fn_r_exp_mn,
            R_non = loc_per_fn_r_not_exp_mn,
            src = loc_per_fn_src_mn) |>
    pivot_longer (c (R_exp, R_non, src)) |>
    rename (type = name, number = value)
x <- readRDS (f) |>
    filter (what == "annual") |>
    select (c (year, loc_per_fn_r_exp_mn, loc_per_fn_r_not_exp_mn,
               loc_per_fn_src_mn)) |>
    rename (R_exp = loc_per_fn_r_exp_mn,
            R_non = loc_per_fn_r_not_exp_mn,
            src = loc_per_fn_src_mn) |>
    pivot_longer (c (R_exp, R_non, src)) |>
    rename (type = name, number = value) |>
    ggplot (aes (x = year, y = number, colour = type)) +
        geom_line () +
        #geom_line (data = loc_cran, show.legend = FALSE, lty = 2) +
        theme (legend.title = element_blank(),
               legend.position = c (0.8, 0.8),
               legend.background = element_rect(fill='transparent', colour='transparent')) +
        ylab ("Lines of Code") +
        scale_y_log10 () +
        ggtitle ("B: LoC per fn") -> p2
```

```{r fig6C-fns-per-year-plot}
nfns_cran <- readRDS (f) |>
    filter (what == "cran_by_year") |>
    select (c (year, n_fns_r_exported, n_fns_r_not_exported, n_fns_src)) |>
    rename (r_exp = n_fns_r_exported,
            r_non = n_fns_r_not_exported,
            src = n_fns_src) |>
    pivot_longer (c (r_exp, r_non, src)) |>
    rename (type = name, number = value)
readRDS (f) |>
    filter (what == "annual") |>
    select (c (year, n_fns_r_exported, n_fns_r_not_exported, n_fns_src)) |>
    rename (r_exp = n_fns_r_exported,
            r_non = n_fns_r_not_exported,
            src = n_fns_src) |>
    pivot_longer (c (r_exp, r_non, src)) |>
    rename (type = name, number = value) |>
    ggplot (aes (x = year, y = number, colour = type)) +
        geom_line () +
        #geom_line (data = nfns_cran, show.legend = FALSE, lty = 2) +
        theme (legend.title = element_blank(),
               legend.position = c (0.15, 0.85),
               legend.background = element_rect(fill='transparent', colour='transparent')) +
        ylab ("Numbers of functions") +
        ggtitle ("C: Total functions") -> p3
```

```{r fig6D-fns-per-file}
nfns_cran <- readRDS (f) |>
    filter (what == "cran_by_year") |>
    select (c (year, n_fns_per_file_r, n_fns_per_file_src)) |>
    rename (R = n_fns_per_file_r,
            src = n_fns_per_file_src) |>
    pivot_longer (c (R, src)) |>
    rename (type = name, number = value)
readRDS (f) |>
    filter (what == "annual") |>
    select (c (year, n_fns_per_file_r, n_fns_per_file_src)) |>
    rename (R = n_fns_per_file_r,
            src = n_fns_per_file_src) |>
    pivot_longer (c (R, src)) |>
    rename (type = name, number = value) |>
    ggplot (aes (x = year, y = number, colour = type)) +
        geom_line () +
        #geom_line (data = nfns_cran, show.legend = FALSE, lty = 2) +
        theme (legend.title = element_blank(),
               legend.position = c (0.85, 0.9),
               legend.background = element_rect(fill='transparent', colour='transparent')) +
        ylab ("Numbers of functions") +
        ggtitle ("D: Functions per file") -> p4
```


```{r fig6-assemble, fig.width = 7, fig.height = 7, fig.cap = "**Fig. 6**"}
(p1 + p2) / (p3 + p4)
```
