
```{r fig5-datafile}
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
```

```{r fig5-external-calls-data-file}
f_fig5_exdat <- file.path (v_data_dir, "fig5-ext-calls.Rds")
calc_ext_calls_dat <- !file.exists (f_fig5_exdat)
```

```{r fig5-external-calls-data, eval = calc_ext_calls_dat}
# select latest packages only
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    group_by (package) |>
    slice_max (date)
x <- x [which (!(is.na (x$external_calls) | x$external_calls == "")), ]
saveRDS (x, f_fig5_exdat)
```

```{r fig5-load-exdat}
x <- readRDS (f_fig5_exdat)
```
```{r fig5-deps-data-file}
f_fig5_deps1 <- file.path (v_data_dir, "fig5-deps1.Rds")
f_fig5_deps2 <- file.path (v_data_dir, "fig5-deps2.Rds")
calc_fig5_deps <- !file.exists(f_fig5_deps1)
```

```{r fig5-deps-calc, eval = calc_fig5_deps}
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)
deps1 <- dependencies (x, cran_by_year = TRUE)
saveRDS (deps1, f_fig5_deps1)
deps2 <- dependencies (x, cran_by_year = FALSE)
saveRDS (deps2, f_fig5_deps2)
```
```{r fig5-prepro}
deps1 <- readRDS (f_fig5_deps1)
deps2 <- readRDS (f_fig5_deps2)
recommended <- recommended_pkgs ()
cp_dat_file <- file.path (v_data_dir, "coupling-data.Rds")
cp_dat_exists <- file.exists (cp_dat_file)
```

```{r fig5-coupling-data-generate, eval = !cp_dat_exists}
cp_dat <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    summarise_coupling_data ()
saveRDS (cp_dat, cp_dat_file)
```



```{r fig5-plot-base-rcmd-ctb}

deps1 <- deps1 [deps1$category == "unique", ]
deps2 <- deps2 [deps2$category == "unique", ]

p1 <- ggplot (deps2, aes (x = year, y = proportion, color = type)) +
    geom_line () +
    geom_line (data = deps1, lty = 2) +
    ggtitle ("A: Proportion of function calls") +
    theme (legend.position = c (0.3, 0.7),
           legend.background = element_rect(fill='transparent', colour='transparent'))
```

```{r fig5-top10-file}
f_top10 <- file.path (v_data_dir, "top10-pkgs.Rds")
calc_top10 <- !file.exists (f_top10)
```


```{r fig5-dep-pkg-calls, eval = calc_top10}
deps <- lapply (seq (nrow (x)), function (i) {
                    # a few have rogue colons at start:
                    ex <- gsub ("^\\:", "", x$external_calls [i])
                    out <- strsplit (strsplit (ex, ",") [[1]], "\\:")
                    lens <- vapply (out, length, integer (1))
                    out <- do.call (rbind, out [which (lens == 3)])
                    
                    this_pkg <- x$package [i]
                    out <- out [which (out [, 1] != this_pkg), , drop = FALSE]

                    out <- cbind (out, rep (x$month [i], nrow (out)))

                    return (out)
           })

deps <- do.call (rbind, deps)

# manual cleaning until https://github.com/ropensci-review-tools/pkgstats/issues/33
# '\' is punct, but 'n' is not, so first get rid of '\n':
deps [, 1] <- gsub ("^\\\\\\\\n", "", deps [, 1])
deps [, 1] <- gsub ("^[[:punct:]]*", "", deps [, 1])
deps <- deps [which (deps [, 1] != ""), ]

deps <- data.frame (package = deps [, 1],
                    date =  lubridate::as_date (as.integer (deps [, 4])),
                    n_total = as.integer (deps [, 2]),
                    n_unique = as.integer (deps [, 3]))

deps <- deps |>
    mutate (year = lubridate::year (date)) |>
    group_by (year, package) |>
    summarise (n = sum (n_unique), .groups = "keep")

top <- deps |>
    group_by (package) |>
    summarise (n = sum (n)) |>
    arrange (desc (n)) |>
    filter (!package %in% c ("base", recommended))

top10 <- deps [deps$package %in% top$package [1:10], ]

saveRDS (top10, f_top10)
```

```{r fig5-deps-p2}
top <- readRDS (f_top10)
prop_top2 <- sum (top$n [1:2]) / sum (top$n [-(1:2)])
prop_top2 <- round (100 * prop_top2, digits = 1)

top |>
    ggplot (aes (x = year, y = n, colour = package)) +
    geom_line () +
    ggtitle ("C: Calls to top 10 packages") +
    ylab ("Number of calls") +
    scale_y_log10 () +
    theme (legend.title = element_blank(),
           legend.position = c (0.20, 0.67),
           legend.background = element_rect(fill='transparent', colour='transparent')) +
    guides (color = guide_legend (ncol = 3)) -> p2
```

```{r fig5-coupling-instability}
cp_dat <- readRDS (cp_dat_file) |>
    select (-c (total_median, unique_median)) |>
    rename (total = total_mean,
            unique = unique_mean) |>
    pivot_longer (cols = c (total, unique)) |>
    rename (instability = value, type = name)
# Values for total and unique are almost identical, so only show unique
cp_dat <- cp_dat [cp_dat$type == "unique", ]
cp_dat$year <- lubridate::year (paste0 (cp_dat$year, "-01-01"))
p3 <- ggplot (cp_dat, aes (x = year, y = instability)) +
    geom_line () +
    ggtitle ("B: Coupling Instability")
```

```{r fig5-assemble, fig.width = 7, fig.height = 7, fig.cap = "**Fig. 5**"}
(p1 | p3) / p2
```
