

<!--

# dependency networks over time

-->

```{r fig9-precalc}
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
graph_data_file <- file.path (v_data_dir, "fig09-graph-metrics.Rds")
graph_intern_data_file <- file.path (v_data_dir, "fig09-graph-metrics-intern.Rds")
calc_graph_data <- !file.exists (graph_data_file)
calc_graph_data_intern <- !file.exists (graph_intern_data_file)
```

```{r fig9-calc-graph-data, eval = calc_graph_data}
# graph metrics for inter-package dependency networks
xraw <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)

graph_one_year <- function (xraw, year = 2015, cran_by_year = TRUE) {

    if (cran_by_year) {
        x <- xraw |>
            filter (year <= !!year) |>
            group_by (package) |>
            slice_max (date)
    } else {
        x <- xraw |>
            filter (year == !!year)
    }

    x <- x [which (!(is.na (x$external_calls) | x$external_calls == "")), ]
    x <- x [which (!(x$imports == "NA" | nchar (x$imports) == 0L)), ]
    if (nrow (x) == 0) {
        return (NULL)
    }

    imports <- lapply (seq (nrow (x)), function (i)
                          data.frame (to = x$package [i],
                                      from = strsplit (x$imports [i], ",") [[1]]))
    imports <- do.call (rbind, imports)
    imports$from <- gsub ("^\\s*|\\s*$", "", imports$from)
    imports$to <- gsub ("^\\s*|\\s*$", "", imports$to)
    imports <- imports [which (!duplicated (imports)), ]

    graph_from_data_frame (imports)
}

graph_metrics <- function (g) {

    dd_in <- degree (g, mode = "in")
    dd_in_zero <- length (which (dd_in < 1e-10)) / length (dd_in)
    dd_in_mean_no0 <- mean (dd_in [which (dd_in > 1e-10)])
    dd_in_mean <- mean (dd_in)

    dd_out <- degree (g, mode = "out")
    dd_out_zero <- length (which (dd_out < 1e-10)) / length (dd_out)
    dd_out_mean_no0 <- mean (dd_out [which (dd_out > 1e-10)])
    dd_out_mean <- mean (dd_out)

    d <- distances (g)
    d [!is.finite (d)] <- NA
    stats <- apply (d, 2, function (i) c (median (i, na.rm = TRUE),
                                          mean (i, na.rm = TRUE)))
    c (dd_in_zero = dd_in_zero,
       dd_in_mean_no0 = dd_in_mean_no0,
       dd_in_mean = dd_in_mean,
       dd_out_zero = dd_out_zero,
       dd_out_mean_no0 = dd_out_mean_no0,
       dd_out_mean = dd_out_mean,
       re = reciprocity (g),
       ad = assortativity_degree (g),
       cb = centr_betw(g, directed = FALSE)$centralization,
       cd = centr_degree(g)$centralization,
       d_med = median (stats [1, ]),
       d_mean = mean (stats [2, ]))
}

years <- sort (unique (xraw$year))
dat <- lapply (years, function (y) {
    g1 <- graph_one_year (xraw, y, cran_by_year = TRUE)
    if (!is.null (g1)) {
        g1 <- c (year = y, graph_metrics (g1), what = 0)
    }
    g2 <- graph_one_year (xraw, y, cran_by_year = FALSE)
    if (!is.null (g2)) {
        g2 <- c (year = y, graph_metrics (g2), what = 1)
    }
    return (rbind (g1, g2))
       })
dat <- data.frame (do.call (rbind, dat))
dat$what [dat$what == 0] <- "cran_by_year"
dat$what [dat$what == 1] <- "annual"

saveRDS (dat, graph_data_file)
```

```{r fig9-intra-pkg-network-stats, eval = calc_graph_data_intern}
xraw <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE)
dat_one_year <- function (xraw, year = 2015) {

    x <- xraw |>
        filter (year <= !!year) |>
        group_by (package) |>
        slice_max (date)

    c (year = year,
       n_edges = mean (x$n_edges [which (!is.na (x$n_edges))]),
       n_edges_r = mean (x$n_edges_r [which (!is.na (x$n_edges_r))]),
       n_edges_src = mean (x$n_edges_src [which (!is.na (x$n_edges_src))]),
       n_clusters = mean (x$n_clusters [which (!is.na (x$n_clusters))]),
       centr_dir_mn = mean (x$centrality_dir_mn [which (!is.na (x$centrality_dir_mn))]),
       centr_dir_md = mean (x$centrality_dir_md [which (!is.na (x$centrality_dir_md))]),
       centr_dir_mn_no0 = mean (x$centrality_dir_mn_no0 [which (!is.na (x$centrality_dir_mn_no0))]),
       centr_dir_md_no0 = mean (x$centrality_dir_md_no0 [which (!is.na (x$centrality_dir_md_no0))]),
       centr_undir_mn = mean (x$centrality_undir_mn [which (!is.na (x$centrality_undir_mn))]),
       centr_undir_md = mean (x$centrality_undir_md [which (!is.na (x$centrality_undir_md))]),
       centr_undir_mn_no0 = mean (x$centrality_undir_mn_no0 [which (!is.na (x$centrality_undir_mn_no0))]),
       centr_undir_md_no0 = mean (x$centrality_undir_md_no0 [which (!is.na (x$centrality_undir_md_no0))]),
       central_edges_dir = mean (x$num_terminal_edges_dir [which (!is.na (x$num_terminal_edges_dir))]),
       term_edges = mean (x$num_terminal_edges_undir [which (!is.na (x$num_terminal_edges_undir))]),
       node_degree_mn = mean (x$node_degree_mn [which (!is.na (x$node_degree_mn))]),
       node_degree_md = mean (x$node_degree_md [which (!is.na (x$node_degree_md))]),
       node_degree_max = mean (x$node_degree_max [which (!is.na (x$node_degree_max))]))
}
years <- sort (unique (xraw$year))
dat <- lapply (years, function (y) dat_one_year (xraw, y))
dat <- data.frame (do.call (rbind, dat))
dat$what <- "cran_by_year"

xs <- xraw |>
    group_by (year) |>
    summarise (
        n_edges = mean (n_edges [which (!is.na (n_edges))]),
        n_edges_r = mean (n_edges_r [which (!is.na (n_edges_r))]),
        n_edges_src = mean (n_edges_src [which (!is.na (n_edges_src))]),
        n_clusters = mean (n_clusters [which (!is.na (n_clusters))]),
        centr_dir_mn = mean (centrality_dir_mn [which (!is.na (centrality_dir_mn))]),
        centr_dir_md = mean (centrality_dir_md [which (!is.na (centrality_dir_md))]),
        centr_dir_mn_no0 = mean (centrality_dir_mn_no0 [which (!is.na (centrality_dir_mn_no0))]),
        centr_dir_md_no0 = mean (centrality_dir_md_no0 [which (!is.na (centrality_dir_md_no0))]),
        centr_undir_mn = mean (centrality_undir_mn [which (!is.na (centrality_undir_mn))]),
        centr_undir_md = mean (centrality_undir_md [which (!is.na (centrality_undir_md))]),
        centr_undir_mn_no0 = mean (centrality_undir_mn_no0 [which (!is.na (centrality_undir_mn_no0))]),
        centr_undir_md_no0 = mean (centrality_undir_md_no0 [which (!is.na (centrality_undir_md_no0))]),
        central_edges_dir = mean (num_terminal_edges_dir [which (!is.na (num_terminal_edges_dir))]),
        term_edges = mean (num_terminal_edges_undir [which (!is.na (num_terminal_edges_undir))]),
        node_degree_mn = mean (node_degree_mn [which (!is.na (node_degree_mn))]),
        node_degree_md = mean (node_degree_md [which (!is.na (node_degree_md))]),
        node_degree_max = mean (node_degree_max [which (!is.na (node_degree_max))]))
xs$what <- "annual"

saveRDS (rbind (dat, xs), graph_intern_data_file)
```

```{r fig9-construct, eval = TRUE}
dat <- readRDS (graph_data_file)
dat_cran <- dat |> filter (what == "cran_by_year")
dat <- dat |> filter (what == "annual")
coeff_fig9_p1 <- max (dat$dd_in_zero) / max (dat$dd_in_mean)
colours_fig9_p1 <- c ("vert_degree" = "red",
                      "not_imported" = "blue")

fig9_p1 <- ggplot (dat, aes (x = year)) +
        geom_line (aes (y = dd_in_mean, col = "vert_degree")) +
        geom_line (aes (y = dd_in_zero / coeff_fig9_p1, col = "not_imported")) +
        geom_line (data = dat_cran, aes (y = dd_in_mean, col = "vert_degree"), lty = 2) +
        geom_line (data = dat_cran, aes (y = dd_in_zero / coeff_fig9_p1, col = "not_imported"), lty = 2) +
        ylab ("Vertex degree") +
        scale_y_continuous (
            sec.axis = sec_axis (~.*coeff_fig9_p1, name = "Prop. non-imported pkgs")) +
        ggtitle ("A: CRAN pkg deps") +
        theme (legend.title = element_blank (),
               legend.position = c (0.2, 0.9),
               legend.background = element_rect(fill='transparent', colour='transparent'))

coeff_fig9_p2 <- max (dat$d_mean) / max (dat$cb)
colours_fig9_p2 <- c ("centr_betw" = "red",
                      "centr_degree" = "green",
                      "mean_dist" = "blue")
fig9_p2 <- ggplot (dat, aes (x = year)) +
        geom_line (aes (y = cb, col = "centr_betw")) +
        geom_line (aes (y = cd, col = "centr_degree")) +
        geom_line (aes (y = d_mean / coeff_fig9_p2, col = "mean_dist")) +
        geom_line (data = dat_cran, aes (y = cb, col = "centr_betw"), lty = 2) +
        geom_line (data = dat_cran, aes (y = cd, col = "centr_degree"), lty = 2) +
        geom_line (data = dat_cran, aes (y = d_mean / coeff_fig9_p2, col = "mean_dist"), lty = 2) +
        ylab ("centrality") +
        scale_y_continuous (
            sec.axis = sec_axis (~.*coeff_fig9_p2, name = "Mean distance")) +
        ggtitle ("B: CRAN network metrics") +
        #guides (color = guide_legend (ncol = 2)) +
        theme (legend.title = element_blank (),
               legend.position = c (0.7, 0.9),
               legend.background = element_rect(fill='transparent', colour='transparent'))
```

```{r fig9-network-internal1}
dat <- readRDS (graph_intern_data_file)
dat_cran <- dat |>
    filter (what == "cran_by_year") |>
    select (year, starts_with ("n_")) |>
    rename (total = n_edges, R = n_edges_r, src = n_edges_src)
coeff_fig9_p3 <- max (dat$n_clusters) / max (dat$n_edges)
colours_fig9_p3 <- c ("total" = "red",
                      "R" = "green",
                      "src" = "blue",
                      "n_clusters" = "orange")
fig9_p3 <- dat |>
    filter (what == "annual") |>
    select (year, starts_with ("n_")) |>
    rename (total = n_edges, R = n_edges_r, src = n_edges_src) |>
    ggplot (aes (x = year)) +
        geom_line (aes (y = total, col = "total")) +
        geom_line (aes (y = R, col = "R")) +
        geom_line (aes (y = src, col = "src")) +
        geom_line (aes (y = n_clusters / coeff_fig9_p3, col = "n_clusters")) +
        #geom_line (data = dat_cran, aes (y = total, col = "total"), lty = 2) +
        #geom_line (data = dat_cran, aes (y = R, col = "R"), lty = 2) +
        #geom_line (data = dat_cran, aes (y = src, col = "src"), lty = 2) +
        #geom_line (data = dat_cran, aes (y = n_clusters / coeff_fig9_p3, col = "n_clusters"), lty = 2) +
        #scale_colour_manual (values = colours_fig9_p3) +
        ylab ("Num. edges") +
        scale_y_continuous (
            sec.axis = sec_axis (~.*coeff_fig9_p3, name = "Num. clusters")) +
        ggtitle ("C: pkg edges and clusters") +
        guides (color = guide_legend (ncol = 2)) +
        theme (legend.title = element_blank (),
               legend.position = c (0.5, 0.15),
               legend.background = element_rect(fill='transparent', colour='transparent'))
```

```{r fig9-network-internal2}
dat <- readRDS (graph_intern_data_file)
dat_cran <- dat |>
    filter (what == "cran_by_year") |>
    select (year, centr_undir_mn, centr_dir_mn, node_degree_mn, term_edges) |>
    rename (centr_undir = centr_undir_mn,
            centr_dir = centr_dir_mn,
            vert_degree = node_degree_mn) |>
    mutate (vert_degree = vert_degree * 10)
coeff_fig9_p4 <- max (dat$term_edges) / max (dat$centr_undir_mn)
colours_fig9_p4 <- c ("centr_undir" = "red",
                      "centr_dir" = "green",
                      "vert_degree" = "blue",
                      "term_edges" = "orange")

fig9_p4 <- dat |>
    filter (what == "annual") |>
    select (year, centr_undir_mn, centr_dir_mn, node_degree_mn, term_edges) |>
    rename (centr_undir = centr_undir_mn,
            centr_dir = centr_dir_mn,
            vert_degree = node_degree_mn) |>
    mutate (vert_degree = vert_degree * 10) |>
    ggplot (aes (x = year)) +
        geom_line (aes (y = centr_undir, col = "centr_undir")) +
        geom_line (aes (y = centr_dir, col = "centr_dir")) +
        geom_line (aes (y = vert_degree / coeff_fig9_p4, col = "vert_degree")) +
        geom_line (aes (y = term_edges / coeff_fig9_p4, col = "term_edges")) +
        #geom_line (data = dat_cran, aes (y = centr_undir, col = "centr_undir"), lty = 2) +
        #geom_line (data = dat_cran, aes (y = centr_dir, col = "centr_dir"), lty = 2) +
        #geom_line (data = dat_cran, aes (y = vert_degree / coeff_fig9_p4, col = "vert_degree"), lty = 2) +
        #geom_line (data = dat_cran, aes (y = term_edges / coeff_fig9_p4, col = "term_edges"), lty = 2) +
        scale_y_continuous (
            sec.axis = sec_axis (~.*coeff_fig9_p4, name = "Vert. degree (*10) / Term. edges")) +
        ggtitle ("D: pkg centrality metrics") +
        guides (color = guide_legend (ncol = 2)) +
        theme (legend.title = element_blank (),
               legend.position = c (0.5, 0.45),
               legend.background = element_rect(fill='transparent', colour='transparent'))
```


```{r fig9-assemble, echo = FALSE, message = FALSE, fig.width = 7, fig.height = 7, fig.cap = "**Figure 9** Network metrics"}
(fig9_p1 + fig9_p2) / (fig9_p3 + fig9_p4)
```
