
```{r recommended-pkgs}
recommended_pkgs <- function () {

    u <- "https://github.com/wch/r-source/tree/trunk/src/library"
    r <- rvest::read_html (u)

    a <- rvest::html_elements (r, "div") |>
        rvest::html_elements ("a")

    titles <- rvest::html_attr (a, "title")
    classes <- rvest::html_attr (a, "class")
    recommended <- titles [grep ("primary", classes)]
    index <- which (!(is.na (recommended) |
                      grepl ("\\.|^Rec|^base", recommended)))
    recommended <- recommended [index]

    return (recommended)
}

recommended <- recommended_pkgs ()
```

```{r external-calls-data}
datafile <- file.path (here, "data-raw", "pkgstats-results.Rds")
# select latest packages only
x <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    mutate (year = lubridate::year (date)) |>
    group_by (package) |>
    slice_max (date)
x <- x [which (!(is.na (x$external_calls) | x$external_calls == "")), ]
```


```{r all-deps}
deps <- lapply (seq (nrow (x)), function (i) {
                    # a few have rogue colons at start:
                    ex <- gsub ("^\\:", "", x$external_calls [i])
                    out <- strsplit (strsplit (ex, ",") [[1]], "\\:")
                    lens <- vapply (out, length, integer (1))
                    out <- do.call (rbind, out [which (lens == 3)])
                    
                    this_pkg <- x$package [i]
                    out <- out [which (out [, 1] != this_pkg), , drop = FALSE]

                    n_total <- as.integer (out [, 2])
                    n_unique <- as.integer (out [, 3])
                    pkg <- out [, 1]

                    i_base <- which (pkg == "base")
                    i_rcmd <- which (pkg %in% recommended)
                    i_ctb <- seq_along (pkg) [-c (i_base, i_rcmd)]

                    n <- nrow (out)

                    return (c (
                        package = this_pkg,
                        month = x$month [i],
                        n_total_base <- sum (n_total [i_base]),
                        n_total_rmcd <- sum (n_total [i_rcmd]),
                        n_total_ctb <- sum (n_total [i_ctb]),

                        n_unique_base <- sum (n_unique [i_base]),
                        n_unique_rmcd <- sum (n_unique [i_rcmd]),
                        n_unique_ctb <- sum (n_unique [i_ctb])
                    ))
})

deps <- do.call (rbind, deps)
```

```{r deps-post-process}
deps_full <- data.frame (package = deps [, 1],
                         date =  lubridate::as_date (as.integer (deps [, 2])),
                         n_total_base = as.integer (deps [, 3]),
                         n_total_rmcd = as.integer (deps [, 4]),
                         n_total_ctb = as.integer (deps [, 5]),
                         n_unique_base = as.integer (deps [, 6]),
                         n_unique_rmcd = as.integer (deps [, 7]),
                         n_unique_ctb = as.integer (deps [, 8]))

deps <- deps_full |>
    mutate (year = lubridate::year (date),
            n_total = n_total_base + n_total_rmcd + n_total_ctb,
            n_unique = n_unique_base + n_unique_rmcd + n_unique_ctb) |>
    group_by (year) |>
    summarise (base_total = sum (n_total_base) / sum (n_total),
               recommended_total = sum (n_total_rmcd) / sum (n_total),
               contributed_total = sum (n_total_ctb) / sum (n_total),
               base_unique = sum (n_unique_base) / sum (n_unique),
               recommended_unique = sum (n_unique_rmcd) / sum (n_unique),
               contributed_unique = sum (n_unique_ctb) / sum (n_unique))

deps <- pivot_longer (deps,
                      cols = c (base_total, recommended_total, contributed_total,
                                base_unique, recommended_unique, contributed_unique),
                      names_to = c ("total", "unique"),
                      names_sep = "\\_") |>
    rename (proportion = value,
            type = total,
            category = unique)
```



```{r plot-base-rcmd-ctb}

#ggplot (deps, aes (x = year, y = proportion, color = type)) +
#    geom_line () +
#    facet_wrap (~category) +
#    theme (legend.position = c (0.1, 0.7),
#           legend.background = element_rect(fill='transparent', colour='transparent'))

deps <- deps [deps$category == "unique", ]

p1 <- ggplot (deps, aes (x = year, y = proportion, color = type)) +
    geom_line () +
    ggtitle ("A: Proportion of function calls") +
    theme (legend.position = c (0.3, 0.7),
           legend.background = element_rect(fill='transparent', colour='transparent'))
```


```{r dep-pkg-calls}
deps <- lapply (seq (nrow (x)), function (i) {
                    # a few have rogue colons at start:
                    ex <- gsub ("^\\:", "", x$external_calls [i])
                    out <- strsplit (strsplit (ex, ",") [[1]], "\\:")
                    lens <- vapply (out, length, integer (1))
                    out <- do.call (rbind, out [which (lens == 3)])
                    
                    this_pkg <- x$package [i]
                    out <- out [which (out [, 1] != this_pkg), , drop = FALSE]

                    out <- cbind (out, rep (x$month [i], nrow (out)))

                    return (out)
           })

deps <- do.call (rbind, deps)

# manual cleaning until https://github.com/ropensci-review-tools/pkgstats/issues/33
# '\' is punct, but 'n' is not, so first get rid of '\n':
deps [, 1] <- gsub ("^\\\\\\\\n", "", deps [, 1])
deps [, 1] <- gsub ("^[[:punct:]]*", "", deps [, 1])
deps <- deps [which (deps [, 1] != ""), ]

deps <- data.frame (package = deps [, 1],
                    date =  lubridate::as_date (as.integer (deps [, 4])),
                    n_total = as.integer (deps [, 2]),
                    n_unique = as.integer (deps [, 3]))

deps <- deps |>
    mutate (year = lubridate::year (date)) |>
    group_by (year, package) |>
    summarise (n = sum (n_unique), .groups = "keep")

top <- deps |>
    group_by (package) |>
    summarise (n = sum (n)) |>
    arrange (desc (n)) |>
    filter (!package %in% c ("base", recommended))

top10 <- deps [deps$package %in% top$package [1:10], ]

prop_top2 <- sum (top$n [1:2]) / sum (top$n [-(1:2)])
prop_top2 <- round (100 * prop_top2, digits = 1)

deps2020 <- deps [deps$year == 2020, ]
```

```{r deps-p2}
p2 <- ggplot (top10, aes (x = year, y = n, colour = package)) +
    geom_line () +
    ggtitle ("B: Calls to top 10 packages") +
    ylab ("Number of calls") +
    scale_y_log10 () +
    theme (legend.position = c (0.2, 0.65),
           legend.background = element_rect(fill='transparent', colour='transparent'))
```


<!--

# dependency networks over time

-->

```{r}
graph_data_file <- file.path (here, "vignettes", "graph-metrics.Rds")
calc_graph_data <- !file.exists (graph_data_file)
```

```{r calc-graph-data, eval = calc_graph_data}
xraw <- load_pkgstats_data (datafile, raw = TRUE, latest = FALSE) |>
    mutate (year = lubridate::year (date))

dat_one_year <- function (xraw, year = 2015) {

    x <- xraw |>
        filter (year <= !!year) |>
        group_by (package) |>
        slice_max (date)
    x <- x [which (!(is.na (x$external_calls) | x$external_calls == "")), ]
    x <- x [which (!(x$imports == "NA" | nchar (x$imports) == 0L)), ]
    if (nrow (x) == 0) {
        return (NULL)
    }

    imports <- lapply (seq (nrow (x)), function (i)
                          data.frame (x$package [i],
                                      imports = strsplit (x$imports [i], ",") [[1]]))
    imports <- do.call (rbind, imports)
    imports <- data.frame (from = gsub ("^\\s*|\\s*$", "", imports [, 1]),
                           to = gsub ("^\\s*|\\s*$", "", imports [, 2]))
    imports <- imports [which (!duplicated (imports)), ]

    graph_from_data_frame (imports)
}

graph_metrics <- function (g) {

    dd_in <- degree_distribution (g, mode = "in")
    dd_in_zero <- length (which (dd_in < 1e-10)) / length (dd_in)
    dd_in_mean <- mean (dd_in [which (dd_in > 1e-10)])
    dd_in_med <- median (dd_in [which (dd_in > 1e-10)])
    dd_out <- degree_distribution (g, mode = "out")
    dd_out_zero <- length (which (dd_out < 1e-10)) / length (dd_out)
    dd_out_mean <- mean (dd_out [which (dd_out > 1e-10)])
    dd_out_med <- median (dd_out [which (dd_out > 1e-10)])

    d <- distances (g)
    d [!is.finite (d)] <- NA
    stats <- apply (d, 2, function (i) c (median (i, na.rm = TRUE),
                                          mean (i, na.rm = TRUE)))
    c (dd_in_zero = dd_in_zero,
       dd_in_mean = dd_in_mean,
       dd_in_med = dd_in_med,
       dd_out_zero = dd_out_zero,
       dd_out_mean = dd_out_mean,
       dd_out_med = dd_out_med,
       re = reciprocity (g),
       ad = assortativity_degree (g),
       cb = centr_betw(g, directed = FALSE)$centralization,
       cd = centr_degree(g)$centralization,
       d_med = median (stats [1, ]),
       d_mean = mean (stats [2, ]))
}

years <- sort (unique (xraw$year))
dat <- lapply (years, function (y) {
    g <- dat_one_year (xraw, y)
    if (is.null (g)) {
        return (NULL)
    }
    c (year = y, graph_metrics (g))
       })
dat <- data.frame (do.call (rbind, dat))

saveRDS (dat, graph_data_file)
```

```{r}
dat <- readRDS (graph_data_file)
dat_dd <- pivot_longer (dat, cols = c (dd_in_zero, dd_in_mean, dd_out_mean)) |>
    select (c (year, name, value)) |>
    mutate (name = gsub ("^dd\\_", "", name))
dat_cd <- pivot_longer (dat, cols = c (cb, cd, d_mean)) |>
    select (c (year, name, value)) |>
    mutate (name = case_when (
                name == "cb" ~ "centr_betw",
                name == "cd" ~ "centr_degree",
                name == "d_mean" ~ "dist_mean"))

p3 <- ggplot (dat_dd, aes (x = year, y = value, color = name)) +
    geom_line () +
    ggtitle ("C: Package dependencies") +
    theme (legend.position = c (0.3, 0.7),
           legend.background = element_rect(fill='transparent', colour='transparent'))

p4 <- ggplot (dat_cd, aes (x = year, y = value, color = name)) +
    geom_line () +
    ggtitle ("D: Network Metrics") +
    theme (legend.position = c (0.3, 0.7),
           legend.background = element_rect(fill='transparent', colour='transparent'))
```

```{r fig5, echo = FALSE, message = FALSE, fig.cap = "**Figure 5** Relative proportions of base, recommended, and contributed packages over time."}
(p1 + p2) / (p3 + p4)
```
